import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
  root: {
    margin: "1rem 0 5rem 0",
    fontFamily: "Roboto",
  },
  heading: {
    color: theme.palette.primary.main,
    paddingLeft: "1rem",
  },
  heading2: {
    color: theme.palette.text.primary,
    margin: 0,
    cursor: "pointer",
  },
  flex: {
    display: "flex",
    margin: "auto",
    maxWidth: "1000px",
    textAlign: "center",
  },
  p: {
    color: "white",
    margin: 0,
    cursor: "pointer",
    display: "block",
    fontSize: "1.5em",
  },
  button_div: {
    marginTop: "40px",
    marginBottom: "40px",
    textAlign: "center",
  },
  head_div: {
    marginTop: "40px",
    marginBottom: "40px",
    textAlign: "center",
  },
  url_container: {
    minWidth: "350px",
    maxWidth: "350px",
    padding: "20px",
    background: "#2ab7ca",
    borderRadius: "5px",
    margin: "auto",
  },
  url_div: {
    textAlign: "center",
    margin: "auto",
  },
  url_p: {
    color: "white",
    margin: 0,
    cursor: "pointer",
    display: "block",
    fontSize: "2.5em",
  },
  ssl_container: {
    minWidth: "350px",
    maxWidth: "350px",
    padding: "20px",
    background: "#2ab7ca",
    borderRadius: "5px",
    textAlign: "center",
    margin: "auto",
    marginTop: "20px",
    marginBottom: "20px",
  },
  ssl_div: {
    textAlign: "right",
  },
  ssl_para_issue: {
    color: "green",
    fontSize: "1em",
    margin: "0",
    marginTop: "10px",
  },
  ssl_para_expire: {
    color: "#851e3e",
    fontSize: "1em",
    margin: "0",
  },
  wcag_container: {
    minWidth: "350px",
    maxWidth: "350px",
    padding: "20px",
    background: "#fe4a49",
    borderRadius: "5px",
    textAlign: "center",
    margin: "auto",
    marginTop: "20px",
    marginBottom: "20px",
  },
  wcag_container_warn: {
    minWidth: "350px",
    maxWidth: "350px",
    padding: "20px",
    background: "#fed766",
    borderRadius: "5px",
    textAlign: "center",
    margin: "auto",
    marginTop: "20px",
    marginBottom: "20px",
  },
  score_div: {
    textAlign: "center",
    margin: "auto",
    marginLeft: "400px",
    padding: "30px",
    display: "flex",
  },
  score_val: {
    margin: "auto",
    padding: "10px",
    marginLeft: "10px",
    marginRight: "10px",
  },
  score_ssl: {
    color: "#7bc043",
    margin: 0,
    cursor: "pointer",
    display: "block",
    fontSize: "2.5em",
  },
  score_cookie: {
    color: "#2ab7ca",
    margin: 0,
    cursor: "pointer",
    display: "block",
    fontSize: "2.5em",
  },
  score_ada: {
    color: "#fed766",
    margin: 0,
    cursor: "pointer",
    display: "block",
    fontSize: "2.5em",
  },
  score_text: {
    color: "#fe4a49",
    margin: 0,
    cursor: "pointer",
    display: "block",
    fontSize: "2.5em",
  },
  para: {
    color: theme.palette.primary.main,
    margin: 0,
    cursor: "pointer",
    display: "block",
    fontSize: "1.5em",
  },
  score_loader1: {
    marginLeft: "85px",
  },
  score_border: {
    padding: "20px",
    border: "2px solid red",
    borderRadius: "50%",
    width: "90px",
    borderColor: theme.palette.primary.main,
    marginBottom: "15px",
    margin: "auto",
  },
}));

export default useStyles;
